# Generated by Django 4.1.4 on 2023-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default='default value', max_length=300),
            preserve_default=False,
        ),
    ]
