# Generated by Django 4.1.4 on 2023-02-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, default='post_default.jpg', null=True, upload_to='post_images'),
        ),
    ]
