# Generated by Django 4.2.7 on 2023-12-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(blank=True, default='post_default.jpg', null=True, upload_to='post_images/'),
        ),
    ]
