# Generated by Django 4.1.4 on 2023-03-16 22:27

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='./media/default.png', null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='media/profile_images'),
        ),
    ]
